name: Save Results

on:
  repository_dispatch:
    types: [save-result]

jobs:
  save-result:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create Results File
        run: |
          mkdir -p results
          echo "${{ github.event.client_payload.content }}" > "results/${{ github.event.client_payload.filename }}"
      
      - name: Commit and Push Changes
        run: |
          git add results/
          git commit -m "Save result: ${{ github.event.client_payload.filename }}"
          git push https://x-access-token:${{ secrets.JURYTEST_TOKEN }}@github.com/lshang-max/Jury-Test.git HEAD:main

