name: Upload File

on:
  repository_dispatch:
    types: [save-result]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create file
        run: |
          echo "${{ github.event.client_payload.content }}" > results/${{ github.event.client_payload.filename }}

      - name: Commit and push
        run: |
          git add results/
          git commit -m "Add results file: ${{ github.event.client_payload.filename }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.JURYTEST_TOKEN }}  # 使用 GitHub Secrets

